### ISSUE TITLE
call fmt.Printf: unknown or uncallable function

### ISSUE THREAD

**Issue by smallnest** [zeebo/goof#4]
I run the simple demo on Mac osx but it can't run

```go
package main

import (
	"fmt"

	"github.com/zeebo/goof"
)

func main() {
	var troop goof.Troop
	out, err := troop.Call("fmt.Printf", "hello %s", []interface{}{"world"})
	if err != nil { // some error calling the function
		panic(err)
	}
	n, err := out[0].(int), out[1].(error)
	if err != nil {
		panic(err)
	}
	fmt.Println("wrote", n, "bytes")

}
```

go env:

```
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yuepan/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gq/jd9v5dd95p570hkztblb8ht40000gn/T/go-build786720216=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

go version:

```
go version go1.8.1 darwin/amd64
```

**Comment by zeebo** [comment]
So Go does dead code elimination, which means that if `fmt.Printf` isn't called elsewhere in the binary somewhere, then goof won't be able to call it.

:(

try changing the `fmt.Println` line at the end to something like `fmt.Printf("wrote %d bytes\n", n)`. I'll update the README so that it Just Works™.

**Comment by zeebo** [comment]
GUESS WHAT? It doesn't even work.

Before I did open sourcing, I attempted to convert it to use the stdlib dwarf packages instead of the golang.org/x/debug/dwarf packages because who wants dependencies?

Turns out, I did. Because it doesn't work and I apparently thought I had tests around basic things like "can it find a string type appropriately" but no, it can't, and I don't.
